(() => {
  const style = document.createElement('style');
  style.textContent = `.request-modal-backdrop{display:none;position:fixed;inset:0;z-index:30;background:rgba(3,5,20,.8);padding:1rem;align-items:center;justify-content:center}.request-modal-backdrop.open{display:flex}.request-modal{position:relative;width:min(620px,100%);max-height:calc(100vh - 2rem);overflow:auto;background:#fff2f8;color:#090d2a;padding:2.2rem;box-shadow:0 20px 80px rgba(0,0,0,.4)}.request-modal h2{font-family:Georgia,'Times New Roman',serif;font-size:clamp(2.3rem,6vw,4rem);font-weight:400;line-height:.92;margin:.7rem 0}.request-modal-intro{color:#53618a;font-size:.88rem;line-height:1.6;margin:0 0 1.4rem}.request-field{display:block;margin:1rem 0}.request-field span{display:block;color:#53618a;font-size:.63rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase;margin-bottom:.45rem}.request-field input,.request-field textarea{display:block;width:100%;border:1px solid #c7ccdf;background:#fff;color:#090d2a;font:inherit;padding:.75rem}.request-field textarea{min-height:120px;resize:vertical}.request-files{border:1px dashed #aeb8dc;padding:.8rem;color:#53618a;font-size:.78rem}.request-files input{width:100%;margin-top:.5rem}.request-file-note{display:block;margin-top:.45rem;font-size:.7rem;line-height:1.45}.request-actions{display:flex;align-items:center;gap:1rem;margin-top:1.3rem}.request-submit{min-height:46px;border:1px solid #ff6eb4;background:#ff6eb4;color:#090d2a;padding:0 1.1rem;font-size:.68rem;font-weight:900;letter-spacing:.13em;text-transform:uppercase;cursor:pointer}.request-submit:hover{background:#090d2a;color:#fff2f8}.request-close{position:absolute;right:.7rem;top:.55rem;width:38px;height:38px;border:0;background:transparent;color:#090d2a;font-size:1.5rem;cursor:pointer}.request-status{color:#53618a;font-size:.72rem;line-height:1.4}.request-nav-button{border:1px solid rgba(255,240,248,.35);background:transparent;color:inherit;padding:.65rem .85rem;font:inherit;font-size:.7rem;font-weight:800;letter-spacing:.13em;text-transform:uppercase;cursor:pointer}.request-nav-button:hover{border-color:#ff6eb4;color:#ff6eb4}@media(max-width:500px){.request-modal{padding:1.5rem}.request-actions{align-items:flex-start;flex-direction:column}}`;
  document.head.appendChild(style);

  const backdrop = document.createElement('div');
  backdrop.className = 'request-modal-backdrop';
  backdrop.innerHTML = `<section class="request-modal" role="dialog" aria-modal="true" aria-labelledby="request-title"><button class="request-close" type="button" aria-label="Close request form">×</button><div class="eyebrow">Custom work</div><h2 id="request-title">Request a build.</h2><p class="request-modal-intro">Tell us what you have in mind. Share the idea, the details, and any reference pictures. Nick will follow up at <strong>nick@lfhproductionsllc.com</strong>.</p><form id="request-form"><label class="request-field"><span>Your name</span><input name="name" required autocomplete="name"></label><label class="request-field"><span>Your email</span><input name="email" type="email" required autocomplete="email"></label><label class="request-field"><span>What would you like built?</span><textarea name="message" required></textarea></label><label class="request-field request-files"><span>Reference pictures</span><input name="pictures" type="file" accept="image/*" multiple><small class="request-file-note">Pictures will be selected here for your request. When your email app opens, attach the selected files before sending.</small></label><div class="request-actions"><button class="request-submit" type="submit">Open email</button><span class="request-status" aria-live="polite"></span></div></form></section>`;
  document.body.appendChild(backdrop);

  const open = () => { backdrop.classList.add('open'); document.body.classList.add('request-open'); backdrop.querySelector('input').focus(); };
  const close = () => { backdrop.classList.remove('open'); document.body.classList.remove('request-open'); };
  document.querySelectorAll('[data-request-build]').forEach(button => button.addEventListener('click', open));
  backdrop.querySelector('.request-close').addEventListener('click', close);
  backdrop.addEventListener('click', event => { if (event.target === backdrop) close(); });
  document.addEventListener('keydown', event => { if (event.key === 'Escape') close(); });
  backdrop.querySelector('form').addEventListener('submit', event => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const files = [...(backdrop.querySelector('[name="pictures"]').files || [])];
    const body = `Name: ${form.get('name')}\nEmail: ${form.get('email')}\n\nBuild request:\n${form.get('message')}\n\nReference files selected: ${files.length ? files.map(file => file.name).join(', ') : 'None'}`;
    window.location.href = `mailto:nick@lfhproductionsllc.com?subject=${encodeURIComponent('Spinnlitz build request')}&body=${encodeURIComponent(body)}`;
    backdrop.querySelector('.request-status').textContent = files.length ? 'Your email app is opening. Please attach the selected pictures before sending.' : 'Your email app is opening.';
  });
})();
